### PR TITLE
Make installesion for config

### PR DESCRIPTION
**Pull request by erikiorai**
So i found error in python2 after installesion of requaerement.txt

### CODE REVIEW

**Comment by erikiorai** [comment]
>

**Comment by spotlightishere** [comment]
I'm not sure the branch multilanguage is ready to be merged yet, sorry 😅

**Comment by erikiorai** [comment]
Oups wrong pull request delete that pull request

**Comment by larsenv** [comment]
Facedesk

**Comment by Artuto** [comment]
HOW YOU DARE TO CLOSE THIS

**Comment by larsenv** [comment]
I'm blocking you from our GitHub.

**Comment by dakrk** [comment]
kek

**Comment by KcrPL** [comment]
![]​(​https://imgur.com/vU78SNP.gif)

**Comment by KcrPL** [comment]
xD

**Pull request closed without merging**
