### PR TITLE
Rewriting a parser in Python

### PR DESCRIPTION
**Pull request by TheMrIron2**
Author Name for Credits: TheMrIron2
Short Description: Ruby -> Python rewrite
Long Description: Just rewrote newsmainichi in Python from Ruby due to comment (for now)

### CODE REVIEW

**Comment by larsenv** [comment]
We discussed in DM that this won't do any good and I'm using ruby for now until I find a solution.

**Comment by TheMrIron2** [comment]
This code has issues with parsing and I'm most likely not going to try and fix this because there's no foreseeable workaround that will work well

**Comment by dakrk** [comment]
ok

**Pull request closed without merging**
