### PR TITLE
Re-organized russian cities for forecast channel; added Yekaterinburg

### PR DESCRIPTION
**Pull request by aovanessian**
Author Name for Credits: aovanessian
Short Description: Re-organized list of Russian cities.
Long Description: Added weathercities100 dict for users from Russia (if there are any); kept all the cities in international dict as well, since otherwise there's great expanses of featureless terrain and no data.

### CODE REVIEW

**Comment by larsenv** [comment]
Looks good but we need to fix the problem with the EULA before we can even do Russia (I believe one or two people want to use RC24 in Russia)

I’m not adding Yekaterinburg to the international city list, but thanks.

**Comment by KcrPL** [comment]
Can we even support Russia with these letters? (i mean: Д, Ж. Л, Ф)

If I remember correctly, Wii doesn't even support these.

**Comment by aovanessian** [comment]
@larsenv, Yekaterinburg is the third largest city in Russia (after Moscow and Saint-Petersbourg); think it deserves a place in the international list, but it's up to you.

@KcrPL, sent a test letter to my wii in Russian - cyrillic characters showed up correctly.

**Comment by KcrPL** [comment]
@aovanessian Really? Good :P :ok_hand:

**Comment by KcrPL** [comment]
Oh and there should be more Russia cities on the map (at least for me), Russia is big :P

**Pull request merged**
